name: sound
channels:
- anaconda
- defaults
- conda-forge
- menpo
dependencies:
- bleach=1.5.0=py36_0
- cudatoolkit=8.0=3
- cudnn=7.0.5=cuda8.0_0
- entrypoints=0.2.3=py36h1aec115_2
- gmp=6.1.2=h6c8ec71_1
- h5py=2.7.1=py36h3585f63_0
- hdf5=1.10.1=h9caa474_1
- html5lib=0.9999999=py36_0
- ipykernel=4.8.2=py36_0
- ipython=6.2.1=py36h88c514a_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36ha16c418_0
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter_client=5.2.2=py36_0
- jupyter_core=4.4.0=py36h7c827e3_0
- keras-gpu=2.1.4=py36_0
- libgcc-ng=7.2.0=h7cc24e2_2
- libgfortran-ng=7.2.0=h9f7466a_2
- libprotobuf=3.5.1=h6f1eeef_0
- libsodium=1.0.15=hf101ebd_0
- libstdcxx-ng=7.2.0=h7a57d05_2
- markdown=2.6.11=py36_0
- markupsafe=1.0=py36hd9260cd_1
- mistune=0.8.3=py36_0
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- notebook=5.4.0=py36_0
- pandoc=1.19.2.1=hea2e7c5_1
- pandocfilters=1.4.2=py36ha6701b7_1
- parso=0.1.1=py36h35f843b_0
- pexpect=4.4.0=py36_0
- pickleshare=0.7.4=py36h63277f8_0
- prompt_toolkit=1.0.15=py36h17d85b1_0
- protobuf=3.5.1=py36hf484d3e_0
- ptyprocess=0.5.2=py36h69acd42_0
- pygments=2.2.0=py36h0d3125c_0
- pyyaml=3.12=py36hafb9ca4_1
- pyzmq=17.0.0=py36h14c3975_0
- send2trash=1.5.0=py36_0
- simplegeneric=0.8.1=py36_2
- tensorflow-gpu=1.4.1=0
- tensorflow-gpu-base=1.4.1=py36h01caf0a_0
- tensorflow-tensorboard=1.5.1=py36hf484d3e_0
- terminado=0.8.1=py36_1
- testpath=0.3.1=py36h8cadb63_0
- traitlets=4.3.2=py36h674d592_0
- wcwidth=0.1.7=py36hdf4376a_0
- werkzeug=0.14.1=py36_0
- yaml=0.1.7=had09818_2
- zeromq=4.2.3=h439df22_3
- audioread=2.1.4=py36_2
- backports=1.0=py36_1
- backports.functools_lru_cache=1.5=py36_0
- bunch=1.0.1=py36_0
- bzip2=1.0.6=1
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.22=0
- decorator=4.2.1=py36_0
- expat=2.2.5=0
- ffmpeg=2.8.6=5
- fontconfig=2.12.6=0
- freetype=2.8.1=0
- gettext=0.19.8.1=0
- glib=2.55.0=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- icu=58.2=0
- joblib=0.11=py36_0
- jpeg=9b=2
- kiwisolver=1.0.1=py36_1
- libffi=3.2.1=3
- libiconv=1.15=0
- libpng=1.6.34=0
- librosa=0.6.0=py36_0
- libxcb=1.12=1
- libxml2=2.9.7=0
- matplotlib=2.2.0=py36_0
- ncurses=5.9=10
- openssl=1.0.2n=0
- pcre=8.39=0
- pip=9.0.1=py36_1
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python=3.6.4=0
- python-dateutil=2.6.1=py36_0
- pytz=2018.3=py_0
- qt=5.6.2=7
- readline=7.0=0
- resampy=0.2.0=py36_1
- setuptools=38.5.2=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- tornado=4.5.3=py36_0
- wheel=0.30.0=py36_2
- x264=20131217=3
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- zlib=1.2.11=0
- libgfortran=3.0.0=1
- llvmlite=0.20.0=py36_0
- mkl=2017.0.3=0
- numba=0.35.0=np113py36_0
- numpy=1.13.1=py36_0
- scikit-learn=0.18.2=np113py36_0
- scipy=0.19.1=np113py36_0
- pip:
  - backports.functools-lru-cache==1.5
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-core==4.4.0
  - keras==2.1.4
  - prompt-toolkit==1.0.15
  - tensorflow==1.4.1
prefix: /home/hugolucas/miniconda3/envs/sound

